/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CeaserCipher;

import java.io.Console;

public class App {
    public static void main(String[] args){
        Console myConsole = System.console();
        System.out.println("Enter a string to encrypt:");
        String text = myConsole.readLine();
        System.out.println("Enter a key to encrypt/decrypt with");
        String keyCode = myConsole.readLine();
        Integer yourKey = Integer.parseInt(keyCode);
        CeaserCipher caes = new CeaserCipher();
        String cipher = caes.encrypt(text,yourKey);
        System.out.println("Your encrypted text is "+cipher);
        String decrypt = caes.decrypt(cipher,yourKey);
        System.out.println("Your decrypted text is "+decrypt);
    }
}
